#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#


#--------------------------------------------------------------------------------------------------
# bgb
#--------------------------------------------------------------------------------------------------
# Start by adding usr/local to the path before devtools-2 gets added. 
# This allows devtools-2 to override usr/local.
#
# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#--------------------------------------------------------------------------------------------------
# bgb
#--------------------------------------------------------------------------------------------------
# Added devtools-2 to the environment to pick up gcc 4.8
#
# Start environment allowing access to g++ 4.8.
# scl enable devtoolset-2 zsh
. /opt/rh/devtoolset-2/enable


# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
  if [[ -t 0 || -t 1 ]]; then
    fortune -s
    print
  fi
fi


#--------------------------------------------------------------------------------------------------
# bgb
#--------------------------------------------------------------------------------------------------
# Add my home directory to the front of the path so I can override 
# outdated utilities in devtools-2 (e.g., git).
#
# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/bin
  $path
)
