#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Sourced for all shells, including non-interactive shells.  
# Do not assume any tty is available.
# Recommended use is setting environment variables.
#

#print "running zshenv"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
cdpath=(
   $cdpath
)

#
# Moved to .zlogin so $HOME can be moved before the Redhat devtools-2 directory.
#
# Set the list of directories that Zsh searches for programs.
path=(
#    $HOME/usr/local/{bin,sbin}
    /usr/local/{bin,sbin}
    $path
    /usr/local/ccollab-client
    )

#
# Less
#
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#
if [[ -d "/data/tmp" ]]; then
    export TMPDIR="/data/tmp"
elif [[ -d "/data/$LOGNAME/tmp/tmp" ]]; then
    export TMPDIR="/data/$LOGNAME/tmp/tmp"
else
    if [[ ! -d "$TMPDIR" ]]; then
        export TMPDIR="/tmp/$LOGNAME"
        mkdir -p -m 700 "$TMPDIR"
    fi
fi

TMPPREFIX="${TMPDIR%/}/zsh"
TMPBASE=${TMPDIR}

#export http_proxy="http://10.40.14.56:8080"
#export https_proxy="http://10.40.14.56:8080"
#export ftp_proxy="http://10.40.14.56:8080"
export http_proxy="http://167.76.56.36:911"
export https_proxy="http://167.76.56.36:911"
export ftp_proxy="http://167.76.56.36:911"
export no_proxy=".ten.thomsonreuters.com,stldevnet.reuters.com,.ime.reuters.com,.int.thomsonreuters.com"

#export CMAKE_MODULE_PATH="$HOME/cmake_scripts/CMakeBase"
#export CMAKE_PREFIX_PATH="$HOME/CMakePrefixPath"
#export RDFD_UPDATE_LOCAL_PACKAGES="TRUE"

export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true'

# Disable GUI prompt so it defaults to command line.
unset SSH_ASKPASS

# 
# Set core dump file size to unlimited.
#
ulimit -c unlimited
umask 002
