#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Sourced for all shells, including non-interactive shells.  
# Do not use any commands that produce output or assume a tty is attached.
# Recommended use is setting environment variables.
#

#print "running .zshenv"

# Ensure that a non-login, non-interactive shell has a defined environment.
# Some people insist on setting their PATH here to affect things like ssh.
# Those that do should probably use $SHLVL to ensure that this only happens
# the first time the shell is started (to avoid overriding a customized
# environment).  Also, the various profile/rc/login files all get sourced
# *after* this file, so they will override this value.  One solution is to
# put your path-setting code into a file named .zpath, and source it from
# both here (if we're not a login shell) and from the .zprofile file (which
# is only sourced if we are a login shell).
if [[ "$SHLVL" -eq 1 && ! -o LOGIN ]]; then
    if [[ -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
        source "${ZDOTDIR:-$HOME}/.zprofile" # .zprofile also sources .zpath
    elif [[ -s "${ZDOTDIR:-$HOME}/.zpath" ]]; then
        source "${ZDOTDIR:-$HOME}/.zpath"
    fi
fi

if [[ "$OSTYPE" == darwin* ]]; then
    export BROWSER='open'
fi

#
# Editors
#
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#
if [[ -z "$LANG" ]]; then
    export LANG='en_US.UTF-8'
fi

#
# Paths
#
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

#
# Less
#
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
    export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

# Used by drive (CLI Google Drive client).
# https://github.com/odeke-em/drive
export GOPATH=$HOME/goworkspace
export GOROOT=$HOME/src/go

# Compiler/Linker
#export CXXFLAGS="-std=c++11 -pthread"
export LIBDIR=/usr/local/lib64
export CXXFLAGS="-std=c++1z -L${LIBDIR} -pthread"
export LD_LIBRARY_PATH=${LIBDIR}:${LD_LIBRARY_PATH}
export LD_RUN_PATH=${LIBDIR}:${LD_RUN_PATH}

# DO NOT SET MANPATH.
# /etc/man.conf contains wildcard search rule to find man pages, but 
# those rules will be ignored if a MANPATH environment variable is set.
# Make sure MANPATH has /usr/local pages included.
# https://github.com/sorin-ionescu/prezto/issues/383
