#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# pipe to multiple outputs
setopt MULTIOS

# change cd to pushd
setopt AUTO_PUSHD

# turn off pushd messages
setopt PUSHD_SILENT

# blank pushd goes to home
setopt PUSHD_TO_HOME

# ten second wait when deleting everything
setopt RM_STAR_WAIT

# use magic (this is the default)
setopt ZLE

# flow control - Ctrl+S
setopt NO_FLOW_CONTROL

# prevent "echo "station" > station from clobbering station
setopt NO_CLOBBER

# other globbing stuff - don't know what these are yet
setopt NUMERIC_GLOB_SORT
setopt EXTENDED_GLOB

# vi style incremental search at the command line
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

# scroll through history after first search match is found
bindkey "^P" history-incremental-search-backward
bindkey "^N" history-incremental-search-forward

# search based on what has already been typed
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

# recommended without explanation
bindkey -M vicmd "q" push-line

# get completion even with spaces in names
bindkey -M viins ' ' magic-space

export PATH=/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin

#export PS1="$ "
#export RPS1="%~"

unalias rm

alias ls="ls -F"
alias tmux="tmux -u"
alias hostname="hostname -f"

# Add this to .bashrc or its equivalent 
transfer()
{
    if [ $# -eq 0 ]; then 
        echo "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md";
        return 1;
    fi 

    tmpfile=$( mktemp -t transferXXX );

    if tty -s; then
        basefile=$(basename "$1" | sed -e 's/[^a-zA-Z0-9._-]/-/g');
        curl --progress-bar --upload-file "$1" "https://transfer.sh/$basefile" >> $tmpfile;
    else
        curl --progress-bar --upload-file "-" "https://transfer.sh/$1" >> $tmpfile ;
    fi;

    cat $tmpfile;
    rm -f $tmpfile; 
} 
